backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          format: "MMM D YYYY, hh:mm:ss a ",
        }
      - {
          label: "Updated Date",
          name: "updatedDate",
          widget: "datetime",
          format: "MMM D YYYY, hh:mm:ss a ",
        }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Flair", name: "badge", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "src/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          format: "MMM D YYYY ",
        }
      - {
          label: "Updated Date",
          name: "updatedDate",
          widget: "datetime",
          format: "MMM D YYYY ",
        }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Flair", name: "badge", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
